### PR TITLE
Fix #30 and #29

### LINKED ISSUE #30: Player#getItemInMainHand Does Not Work on 1.8.8
You will receive a `NoSuchMethodError` if you test the plugin on Spigot 1.8.8. This is because 1.8 does not have "dual-wielding" or any such nonsense, so there is no `Player#getItemInMainHand` (The methods in `Inventory` are similar).

This issue can easily be solved by using `Player#getItemInHand`. It's deprecated but it won't break anything in newer versions unless Spigot were to remove the method entirely (And Spigot doesn't do that because they have a reputation for a stable API).

**Error**
https://pastebin.com/gaWm5Mn2

**Reference**
https://github.com/dnyferguson/MineableSpawners/blob/master/src/main/java/com/dnyferguson/mineablespawners/listeners/SpawnerMineListener.java#L112

### PR DESCRIPTION
**Pull request by A248**
Fixes the problems described in #29 and more importantly #30

### CODE REVIEW

**Comment by ghost** [comment]
I'll merge it when you either make the "Dont print all mob types" an option that is disabled by default or remove that part from the PR. If not, ill edit the code myself in a few hours to fix the iteminhand bit

**Comment by A248** [comment]
Go ahead and do it yourself. I don't like console spam.
