### ISSUE TITLE
Player#getItemInMainHand Does Not Work on 1.8.8

### ISSUE THREAD

**Issue by A248** [dnyferguson/MineableSpawners#30]
You will receive a `NoSuchMethodError` if you test the plugin on Spigot 1.8.8. This is because 1.8 does not have "dual-wielding" or any such nonsense, so there is no `Player#getItemInMainHand` (The methods in `Inventory` are similar).

This issue can easily be solved by using `Player#getItemInHand`. It's deprecated but it won't break anything in newer versions unless Spigot were to remove the method entirely (And Spigot doesn't do that because they have a reputation for a stable API).

**Error**
https://pastebin.com/gaWm5Mn2

**Reference**
https://github.com/dnyferguson/MineableSpawners/blob/master/src/main/java/com/dnyferguson/mineablespawners/listeners/SpawnerMineListener.java#L112

**Comment by ghost** [comment]
Fixed in latest, thanks for the catch
